# NumPy in Python

### Loading in NumPy (remember to pip install numpy first)

#### The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype='int32')#array of integers
print(a)


[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])#Array of floats
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Getting Dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Getting shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
# Getting type
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
# Get Size
a.itemsize

4

In [13]:
b.itemsize

8

In [14]:
# Getting total size
a.nbytes

12

In [15]:
b.nbytes

48

#### Accessing/Changing Specific Row Or Column Etc.

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [r, c]
a[1, 5] # First row and fifth column

13

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [20]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [21]:
a[1, 5] = 20 # Changing element at [1,5] to 20
print(a)

a[:, 2] = [1, 2]#changing second column
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [22]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Initialising Different Types Of Arrays

In [26]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s 3-D matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [28]:
# 2*2 matrix of any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [29]:
# Any other number (full_like)
np.full_like(a, 4) #same matrix as a filled with 4


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4,2)#

array([[0.79099378, 0.50694793],
       [0.63521225, 0.78311248],
       [0.31518869, 0.8551542 ],
       [0.98324169, 0.52042913]])

In [31]:
# Random Integer values between -4 to 8 of size 3*3
np.random.randint(-4,8, size=(3,3))

array([[ 1,  6,  2],
       [-2,  2,  1],
       [-3,  3,  1]])

In [32]:
# The identity matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Mathematics

In [35]:
a = np.array([1, 2, 3, 4])
print(a)


[1 2 3 4]


In [36]:
a + 2


array([3, 4, 5, 6])

In [37]:
a - 2


array([-1,  0,  1,  2])

In [38]:
a * 2


array([2, 4, 6, 8])

In [39]:
a / 2


array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1, 0, 1, 0])
a + b


array([2, 2, 4, 4])

In [41]:
a ** 2 #square

array([ 1,  4,  9, 16])

In [42]:
# Take the cos
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [43]:
a = np.ones((2,3))# Matrix of 1s of size 2*3
print(a)

b = np.full((3,2), 2)# Matrix of 2 of size 3*2
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [44]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

###### Reference docs `(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)`


##### Statistics

In [45]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)


1

In [47]:
np.max(stats, axis=1)


array([3, 6])

In [48]:
np.sum(stats, axis=0)

array([5, 7, 9])

#### Reorganising Arrays

In [50]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8,1))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [51]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

##### Loading Data From File