# NumPy in Python

### Loading in NumPy (remember to pip install numpy first)

#### The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype='int32')#array of integers
print(a)


[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])#Array of floats
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]
