# NumPy in Python

### Loading in NumPy (remember to pip install numpy first)

#### The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype='int32')#array of integers
print(a)


[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])#Array of floats
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Getting Dimension
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Getting shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
# Getting type
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
# Get Size
a.itemsize

4

In [13]:
b.itemsize

8

In [14]:
# Getting total size
a.nbytes

12

In [15]:
b.nbytes

48

#### Accessing/Changing Specific Row Or Column Etc.

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [r, c]
a[1, 5] # First row and fifth column

13

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [20]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [21]:
a[1, 5] = 20 # Changing element at [1,5] to 20
print(a)

a[:, 2] = [1, 2]#changing second column
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [22]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])