## Topic 2: NumPy ndarrays for Working with Gridded Data in Python


In [1]:
import os  # operating system
import numpy as np  # arrays and matrix math
import matplotlib.pyplot as plt  # plotting
from scipy import stats  # summary statistics

### Loading The Dataset

In [2]:
porosity_1d_array = np.fromfile('dataset.dat')
print('porosity_1d_array is a ' + str(type(porosity_1d_array)) + '.')

porosity_1d_array is a <class 'numpy.ndarray'>.


#### Previewing The ndarrays

In [3]:
porosity_1d_array

array([ 9.47058121,  9.91782937,  9.9798204 , ..., 10.76326531,
       10.30917151, 10.86594983])

Notice that NumPy constrains the number of displayed elements.
- This prevents us from attempting an impractical visualization of a large number of elements
- We can use NumPy's set_printoptions() function to control the printing of arrays
- We put input as precision and threshold where precision is the number of decimals, threshold is the number elements to trigger summarization.

In [4]:
np.set_printoptions(precision = 3, threshold=100)
porosity_1d_array

array([ 9.471,  9.918,  9.98 , ..., 10.763, 10.309, 10.866])

#### Checking the Size and Dimensions of ndarrays
Now we have an ndarray to work with. We will check the shape now:
- The ndarray member `[my_ndarray].shape` stores the number of dimensions and the size in each dimension in a tuple (an immutable list)

In [5]:
porosity_1d_array.shape

(10000,)

#### Reshaping The ndarray 
We use the member function `[my_ndarray].reshape()` to restore the loaded 1D array to a 2D ndarray

- The inputs are the original array and the new shape as int or tuple of ints.
- In 2D the standard Python order is left to right for each row from top to bottom
- It is possible to set the order = 'C' for C-like index or 'F' for Fortran index

In [6]:
porosity_map = np.reshape(porosity_1d_array, [100, 100]) # reshaping the 1-d array to 100*100
print('The porosity map has a shape ' + str(porosity_map.shape) + '.')
ny = porosity_map.shape[0] #getting the array ny
nx = porosity_map.shape[1] # getting the array nx
print('Our 2D array has number of x cells = ' + str(nx) + ', and y cells = ' + str(ny) + '.')#checking the reshaping

The porosity map has a shape (100, 100).
Our 2D array has number of x cells = 100, and y cells = 100.


#### Flattening The ndarrays
There are times that we want to 'flatten' a multidimensional array to 1D ndarrays
- There is a member function `[my_ndarray].flatten()` to do this.
- We lose the information on endianness, but in some cases that is desirable, for example, when finding the minimum value over the ndarray or plotting a histogram.

In [7]:
flatten_porosity_map = porosity_map.flatten()#flattening the 2d map
print('The flattened porosity map has a shape ' + str(flatten_porosity_map.shape) + '.')

The flattened porosity map has a shape (10000,).


#### Reading And Writing Binary Files
We will now close the loop write out the array and read it back in, to demonstrate the ndarray output member function `[my_ndarray].tofile()`
- We save the map as binary, read and back in
- We compare the 2 ndarrays with the NumPy function `np.array_equal()`

In [8]:
porosity_map.tofile("porosity_test.dat")#saving 2D array to 1D File
porosity_test = np.fromfile('porosity_test.dat')#reading 1D bindary file back to 1D arrat
check = np.array_equal(porosity_map, np.reshape(porosity_test,[100,100])) #checking if loaded is saved or not
print('Is the array we wrote out and read back in the same as the original array? ' + str(check) + '.')

Is the array we wrote out and read back in the same as the original array? True.


#### Writing ASCII Comma Delimited Files
Now we write our map to an comma delimited ASCII file (*.csv).
- These files are readible in any text editor and are easy to load into MS Excel.

In [9]:
# saving our 2D array to 2D comma delimited
np.savetxt("porosity_map.csv", porosity_map, delimiter=",")

#### Reading ASCII Comma Delimited Files
We can load the 2D map back in and confirm the we have the same ndarray that we started with.

In [11]:
porosity_map_test = np.loadtxt("porosity_map.csv", delimiter=",")#loading the csv
test = np.array_equal(porosity_map, porosity_map_test)#checking if the arrays are the same
print('Is the array we wrote out and read back in the same as the original array? ' + str(test) + '.')
print('The loaded array has a shape ' + str(porosity_map_test.shape) + '.')

Is the array we wrote out and read back in the same as the original array? True.
The loaded array has a shape (100, 100).


### Slicing ndArrays
Just like Pandas DataFrames we can slice NumPy ndarrays.
- Some common notation of slicing is as follows -: all, :5 from 0 to 4, 96: from 96 to end and more advanced - 1:10:3 from 1 through 9, take every 3rd row or column.



In [12]:
# first slice of top left corner
top_corner = porosity_map[:5, :5] #extracting type left corner
print('The type for the slice is ' + str(type(top_corner)) + '.')
print('The shape of the slice is ' + str(top_corner.shape) + '.')
top_corner

The type for the slice is <class 'numpy.ndarray'>.
The shape of the slice is (5, 5).


array([[ 9.471,  9.918,  9.98 ,  9.916, 10.699],
       [ 8.676,  8.945,  9.267, 10.003, 11.012],
       [ 9.139,  8.934,  9.878, 10.908, 10.909],
       [ 8.335,  8.695,  9.284, 10.609, 11.524],
       [ 9.359,  9.917, 10.049, 10.772, 11.161]])

> Here we are extracting the first column of the top corner. This is the furthest left column of the top corner.

In [13]:
first_column = top_corner[:, 0]#extracting the first column
print('The shape of the slice is ' + str(first_column.shape) + '.')
first_column

The shape of the slice is (5,).


array([9.471, 8.676, 9.139, 8.335, 9.359])

> Here we have example where we extract the bottom 2 rows.



In [14]:
last_2_rows = top_corner[-2:, :]
print('The shape of the slice is ' + str(last_2_rows.shape) + '.')
last_2_rows

The shape of the slice is (2, 5).


array([[ 8.335,  8.695,  9.284, 10.609, 11.524],
       [ 9.359,  9.917, 10.049, 10.772, 11.161]])